# Install golang 1.16
FROM golang:1.16

WORKDIR /usr/src/app

# project runs in a docker container with port 8080 published
EXPOSE 8080

COPY . .

# Run go build. It will generate a binary named "server"
RUN go build .

# Execute the file
CMD ["./server"]